#!/usr/bin/env bash
set -eo pipefail

echo "WARNING"
echo "This will remove any machine identity stored in /etc/. Continue (y/n)?"
read decision

if [ `echo $decision | tr '[:upper:]' '[:lower:]'` != "y" ]; then
  exit
fi

# Remove any configuration generated by previous runs
sudo rm -f /etc/conjur.identity /etc/conjur.conf /etc/conjur-demo.pem

# Load policy and populate secret values
conjur authn login -u demo -p demo
conjur policy load --as-group security_admin policy/demo-app.yml
conjur variable values add demo-app/api-key "$(openssl rand -hex 20)"

# Create a new host identity to run our application and conjurize the local machine
token="`conjur hostfactory token create demo-app | jq -r ".[0].token"`"
conjur hostfactory host create $token dynamic-host-$(openssl rand -hex 2) | conjurize | sudo sh

# Allow us to use the identity without requiring root
sudo chown $USER /etc/conjur.identity /etc/conjur.conf /etc/conjur-demo.pem

# Build demo application jar file
mvn package

echo -e "\n\n"
echo "Setup complete."
echo "You may now run \"java -jar target/`ls target | grep '.jar$'`\"."